gitOps:
  app: argocd
ingress:
  host: 35.196.249.89.nip.io
  classname: contour
image: index.docker.io/vfarcic/cncf-demo
tag: cncf-demo-sha256-3afb49e71d42b88b34045bb1a898704fdf207bda4a3a5dee3f2012a12cd84c43
templates: helm
crossplane:
  destination: google
production:
  azure:
    resourceGroup: dot-20240123133515
    location: eastus
  google:
    projectId: dot-20240812152736
hyperscaler: aws
secrets: eso
google:
  projectId: ""
